<?php

namespace wcf\acp\page;

use wcf\page\AbstractPage;
use wcf\data\oauth2server\AuthClientList;
use wcf\system\WCF;

class AuthClientListPage extends AbstractPage {
	/**
	 * @inheritDoc
	 */
	public $activeMenuItem = "wcf.acp.menu.oauth2server.authclient.list";

	/**
	 * TODO
	 */
	public $clients = [];
	
	/**
	 * @inheritDoc
	 */
	public function readData() {
		parent::readData(); // TODO: Change the autogenerated stub

		$clientsList = new AuthClientList();
		$clientsList->readObjects();

		$this->clients = $clientsList->getObjects();
	}
	
	/**
	 * @inheritDoc
	 */
	public function assignVariables() {
		parent::assignVariables();

		WCF::getTPL()->assign([
			'clients' => $this->clients
		]);
	}
}
