<?php

namespace wcf\form;

class AuthClientAddForm extends AbstractForm {
	/**
	 * @inheritDoc
	 */
	public function readData() {
		parent::readData(); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function readFormParameters() {
		parent::readFormParameters(); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function validate() {
		parent::validate(); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function assignVariables() {
		parent::assignVariables(); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function save() {
		parent::save(); // TODO: Change the autogenerated stub
	}
}