<?php
/**
 * Created by PhpStorm.
 * User: b.just
 * Date: 10.09.2018
 * Time: 22:12
 */

namespace wcf\action;


use wcf\data\oauth2server\AuthToken;
use wcf\data\oauth2server\AuthTokenEditor;
use wcf\system\exception\IllegalLinkException;

class TokenAction extends AbstractAction {

	private $grantType = null;
	private $code = null;

	/**
	 * @inheritDoc
	 */
	public function readParameters() {
		parent::readParameters(); // TODO: Change the autogenerated stub

		if (isset($_GET["grant_type"]))
			$this->grantType = $_GET["grant_type"];

		if(isset($_GET["code"]))
			$this->code = $_GET["code"];
	}

	/**
	 * @inheritDoc
	 */
	public function execute() {
		parent::execute(); // TODO: Change the autogenerated stub

		if($this->grantType == null)
			throw new IllegalLinkException();

		if($this->code == null)
			throw new IllegalLinkException();

		$authCode = new AuthToken($this->code);
		if($authCode->getObjectID() === 0)
			throw new IllegalLinkException();

		if($authCode->expires < time())
			throw new IllegalLinkException();

		$refreshToken = bin2hex(openssl_random_pseudo_bytes(16));
		AuthTokenEditor::create([
			'token' => $refreshToken,
			"userID" => $authCode->userID,
			"clientID" => $authCode->clientID,
			"tokenType" => "refresh_token",
			"expires" => time() + (60 * 60 * 24 * 30) // Code ist ab aktueller Zeit 30 Tage gültig
		]);

		$accessToken = bin2hex(openssl_random_pseudo_bytes(16));
		$expires_in = time() + (60 * 30); // Code ist ab aktueller Zeit 30 Minuten gültig
		AuthTokenEditor::create([
			'token' => $accessToken,
			"userID" => $authCode->userID,
			"clientID" => $authCode->clientID,
			"tokenType" => "access_token",
			"expires" => $expires_in
		]);

		$json = new \stdClass();
		$json->access_token = $accessToken;
		$json->refresh_token = $refreshToken;
		$json->expires_in = $expires_in;
		$json->token_type = "bearer";
		$json->scope = "email";

		@header('Content-type: application/json');
		echo json_encode($json, JSON_PRETTY_PRINT);

		$this->executed();
		exit;
	}
}
